-- 코드를 입력하세요

SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALED, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'

UNION ALL
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALED, PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY SALED ASC, PRODUCT_ID ASC, USER_ID ASC
;